### ISSUE TITLE
Use entity attribute as optional

### ISSUE THREAD

**Issue by tmjo** [MindFreeze/ha-sankey-chart#31]
Hi,

Thanks for an amazing card, this is really what I've been looking for! I'd love the opportunity to optionally choose an _entity attribute_ instead of only the entity id. Forgive me if this is already a feature, if so I couldn't find it.

An example, using HA utility meter: They keep the attribute `last_period` showing exactly that, the previous number. For instance having a daily, weekly, monthly or yearly energy sensor it would be nice to be able to display yesterday's energy consumption by using the attribute in addition to todays consumption by using the entity state.

Keep up the good work, loved the card!

**Comment by MindFreeze** [comment]
You can do this with templates but I think it would be easy to implement here, so I'll add it when I have time.

**Comment by MindFreeze** [comment]
added in v0.10.0 but I am not sure if your use case will work as you may get a duplicated entity_id. Unfortunately I am not willing to make it more compex than that because I would have to generate a new unique IDs when an attribute is used, which would have to be specified under `chilren` instead of the entity_id, and all that would be difficult to explain in the README.
If the current implementation doesn't work for you, please create custom entities with HA templates.

**Comment by tmjo** [comment]
Thanks a lot! That did exactly what I was looking for!

![image](https://user-images.githubusercontent.com/54450177/183247011-59f68730-a88d-4c1c-b09b-8fb784996117.png)
