### ISSUE TITLE
Override entity unit of measurement

### ISSUE THREAD

**Issue by SAOPP** [MindFreeze/ha-sankey-chart#40]
Hi!

Thanks for da card, it's awesome! :+1: 

I have a suggestion, how 'bout adding the ability to overwrite the value of entities?

I mean, so that u can set a localization value, for example if `W` --> but I want to set to `Вт` and etc...

Something similar has already been implemented, for example, in lovelace-multiple-entity-row, u can find it here: https://github.com/benct/lovelace-multiple-entity-row#secondary-info

Thanks in advance!

**Comment by MindFreeze** [comment]
I'll think about this because it has some implications.

You can do this with template entities. The calculations will still work if the prefix is in latin, like kВт. And handling non latin prefixes is too much work to bother.

**Comment by SAOPP** [comment]
ok, I thought that it would only concern the display, produce entities specifically for the specific card, well, such a solution :) Okay, let's see. Thank u.

**Comment by tadasdanielius** [comment]
There is a problem with intermediate "remaining_child_state" and my guess is that having two level "remaining_child_state" cause an issue, because the top node does not know the units of measurement, since the the middle node is also a virtual node. 

Consider a scenario like 

```
energy
  \/
Lights
\/    \/                 
1F    2F 
   \/
(then actual entities)                        
```
Lights, 1F, 2F are all of type remaining_child_state. That would throw an error and it seems so that it is related to that it does not know the "units of measurement". So, being able to specify "unit_of_measurement" would be a good workaround for this problem as well.
