### ISSUE TITLE
Support for battery

### ISSUE THREAD

**Issue by derhappy** [MindFreeze/ha-sankey-chart#75]
Our house is equipped with multiple (small) solar inverters as well as a central battery and I'm having trouble integrating the battery power in the chart.
When the battery is loading the entity values are positive. If it's discharging the values are negative. 
Since the sun was kind enough to reveal itself for some minutes in the last days, I noticed the chart does not seem to handle negative values; and even if, I'm not sure how to integrate the battery in the chart.
Current state:
If I put the consumers as children behind the battery, it seems like the power is flowing into the battery and directly leaves it again. If the battery is discharged (negative values) it's not visible at all.

Expected state:
I put children behind the battery. If the value for battery is positive, the energy only flows into the battery pretends it has no children. If the value for the battery is negative, the children get energy from the battery, but no energy is flowing into the battery.

**Comment by MindFreeze** [comment]
Negative values are not allowed. 

I have a similar setup. What you need is a template entity in HA that transforms the negative value into a positive one when the battery is charging. Call it battery_charging_power. Then you put your normal discharging entity in the beginning with all the producers and put battery_charging_power in the next section as a consumer and child of the producers (including the other battery entity). Since charging and discharging are mutually exclusive, you will never see the battery charging itself. But it will be in different sections depending on its state

**Comment by derhappy** [comment]
Thanks for your suggested solution. This is indeed what I did to work around this limitation. I was hoping to get around adding yet another entity that's only required for displaying a single graph.
I guess for daily negative kWh consumption data (battery discharge in the morning) we also need to create a dummy?

**Comment by MindFreeze** [comment]
Yep
